source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode 10 caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorBiometricAuth', :path => '../../node_modules/capacitor-biometric-auth'
  pod 'NoteNode', :path => '../../note-node'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end

target 'App' do
  project 'App.xcodeproj'
  
  capacitor_pods
  # Add your Pods here
  
  pod 'RealmSwift', '10.7.7'#再高的版本，realm到json转换需要修改代码
  pod 'SwiftyJSON'
  pod 'KeychainSwift', '~> 19.0'
  
  pod 'Firebase/Core'
  pod 'Firebase'
  
  # Add the pod for Firebase Crashlytics
  pod 'Firebase/Crashlytics'

  # Recommended: Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  
  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'

end

